import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import ts from 'typescript';
const load = (file, extra = {}) => {
 const exports = {};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports,...extra});
 return exports;
};
const {bindTextDoubleTap} = load('src/剧情生图/text-double-tap.ts');
let fine=true, calls=0; const listeners=new Map();
const doc={defaultView:{matchMedia:()=>({matches:fine})},addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:name=>listeners.delete(name)};
const message={matches:()=>false,getAttribute:()=> '4'};
const text={closest:()=>message};
const target={nodeType:1,closest:s=>s.startsWith('#chat')?text:null};
const event={target,clientX:12,clientY:24,preventDefault(){},stopPropagation(){}};
const dispose=bindTextDoubleTap(doc,()=>true,()=>calls++);
assert.deepEqual([...listeners.keys()],['dblclick']);
listeners.get('dblclick')(event); assert.equal(calls,1);
fine=false; listeners.get('dblclick')(event); assert.equal(calls,1);
fine=true; listeners.get('dblclick')({...event,sourceCapabilities:{firesTouchEvents:true}}); assert.equal(calls,1);
dispose();assert.equal(listeners.size,0);
let attached=0;
const {bindChatTextGestures}=load('src/剧情生图/chat-text-gestures.ts',{require:()=>({bindTextDoubleTap:()=>{attached++;return ()=>{};}})});
const mobileCleanup=bindChatTextGestures({defaultView:{matchMedia:()=>({matches:false})},getElementById(){throw Error('mobile must not scan chat');}},()=>true,()=>{});
assert.equal(attached,0);mobileCleanup();
// Run the actual button insertion function with a minimal toolbar adapter.
const source=fs.readFileSync('src/剧情生图/index.ts','utf8');
const fn=source.slice(source.indexOf('function ensureQuickButton('),source.indexOf('function ensureAllQuickButtons('));
let handler, placement, currentSwipe=2, opened;
const empty={length:0};const edit={length:1};const container={length:1,prepend(){placement='fallback';}};
const button={0:{getBoundingClientRect:()=>({left:20,bottom:55})},on:(_,cb)=>handler=cb,insertAfter:el=>{assert.equal(el,edit);placement='after-edit';}};
let exists=false,isUser=false;
const mes={length:1,attr:()=>isUser?'true':'false',hasClass:()=>false,find:s=>s==='.story-image-quick-btn'?{length:exists?1:0}:s==='.mes_edit'?{first:()=>edit}:s==='.mes_buttons'?{first:()=>container}:empty};
const context={useStoryImageSettingsStore:()=>({settings:{enabled:true,behavior:{enableQuickButton:false,enableDoubleClick:false}}}),isRealChatActive:()=>true,retrieveDisplayedMessage:()=>({closest:selector=>{assert.equal(selector,'.mes');return mes;},find:()=>empty}),$:()=>button,tavernDocument:{},getMessageCurrentSwipeId:()=>currentSwipe,getSwipeState:()=>({status:'planned'}),openActionPopover:(...args)=>opened=args};
vm.createContext(context);vm.runInContext(ts.transpileModule(fn,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText+'\nthis.ensure=ensureQuickButton;',context);
context.ensure(4); assert.equal(placement,'after-edit');
currentSwipe=3;handler({preventDefault(){},stopPropagation(){}});assert.equal(opened[0],4);assert.equal(opened[1],3);assert.equal(opened[2].y,55);
placement=null;exists=true;context.ensure(4);assert.equal(placement,null);
exists=false;isUser=true;context.ensure(4);assert.equal(placement,null);
console.log('TOOLBAR_AND_DESKTOP_GESTURE_TESTS_OK');
