import type { OpeningFormSnapshot } from './opening';
export type WorldSection = '世界基础' | '社会生活' | '历史与现状';
export const worldFields = [
  {
    id: 'foundation.overview',
    layer: 'foundation',
    section: '世界基础',
    field: '世界概况',
    title: '世界概况',
    hint: '设定时代的背景、现实或架空基底，以及世界的总体特质。',
    placeholder: '例如：人妖共存的现代海滨都市，表面维持着脆弱的法制平衡。',
    prompt: '说明现实或架空、时代定位，以及世界的一句话特征。只写总览，不展开地理、制度和剧情。',
  },
  {
    id: 'foundation.laws',
    layer: 'foundation',
    section: '世界基础',
    field: '底层规律',
    title: '底层规律与异常法则',
    hint: '打破现实常理的自然、生命或时空规律，以及其生效边界。',
    placeholder: '例如：梦境中遭受的创伤会显现至现实肉体，但仅伤者可见。',
    prompt: '描述自然、生命、时空等底层规律及边界；不写国家法律、科技清单或编辑器机制。普通现实规律无需逐条复述。',
  },
  {
    id: 'foundation.geography',
    layer: 'foundation',
    section: '世界基础',
    field: '地理生态与资源',
    title: '地理生态与关键资源',
    hint: '主要地域风貌、气候环境及各方争夺的核心战略资源。',
    placeholder: '例如：城市沿海而建，内陆常年被未知的重雾与异常生物封锁。',
    prompt: '描述主要地域、气候、生态、关键资源与分布，以及环境的实际限制；不指定开场落脚点，不展开经济制度。',
  },
  {
    id: 'foundation.inhabitants',
    layer: 'foundation',
    section: '世界基础',
    field: '居民与族群',
    title: '主要族群与生理特质',
    hint: '世居物种或族群的生理构造、寿命差异与独特的生存本能。',
    placeholder: '例如：纯血人类与长寿海裔共居，海裔具有微弱感知但畏光。',
    prompt: '描述居民、族群的生理或寿命差异、分布与生存需求；不创造具体 NPC 档案，不把同一族群写成同一种性格。',
  },
  {
    id: 'foundation.technology',
    layer: 'foundation',
    section: '世界基础',
    field: '技术与特殊力量',
    title: '科技水平与超常能力',
    hint: '世界固有的科技层次或超凡力量体系、普及门槛与使用代价。',
    placeholder: '例如：日常科技接近现代，少数觉醒者能将记忆固化为实体晶石。',
    prompt: '描述原有技术或力量能做什么、谁可获得、普及程度与代价；不写现实编辑器，不重复自然公理或制度全文。',
  },
  {
    id: 'society.institutions',
    layer: 'society',
    section: '社会生活',
    field: '权力与制度',
    title: '统治秩序与阶层制度',
    hint: '统治权力归属、核心法令规章、阶级特权与身份准入门槛。',
    placeholder: '例如：各城区由议会自治，外来者必须持有本地居民担保文书。',
    prompt: '描述治理、法律、身份、阶层、权利和义务；不列具体势力的目标和联盟，不以主角遭遇代替制度。',
  },
  {
    id: 'society.economy',
    layer: 'society',
    section: '社会生活',
    field: '经济与基础设施',
    title: '经济支柱与流通秩序',
    hint: '生产生计、主要交易方式、公共服务以及交通与通信网络。',
    placeholder: '例如：以港口走私与转运为支柱经济，依赖通宵渡轮与封闭局域网。',
    prompt: '描述生产、生计、交易、分配、交通、通信与公共服务；可以推导技术的生产影响，但不重复技术原理或文化信条。',
  },
  {
    id: 'society.culture',
    layer: 'society',
    section: '社会生活',
    field: '文化信仰与价值观',
    title: '信仰风俗与道德禁忌',
    hint: '主流信仰崇拜、社会共同认同的价值追求与不可触犯的禁忌。',
    placeholder: '例如：极度敬畏深海与契约，私毁誓言者会被剥夺一切市民权利。',
    prompt: '描述居民相信、重视与忌讳什么，以及群体间的观念差异；不重复作息生活清单，不把信仰自动写成客观真相。',
  },
  {
    id: 'society.daily',
    layer: 'society',
    section: '社会生活',
    field: '日常生活',
    title: '日常生活与市井风貌',
    hint: '普通居民的衣食住行、作息规律与常见的消遣休闲方式。',
    placeholder: '例如：白天在仓储区与船坞劳作，入夜后聚集在地下酒馆消遣买醉。',
    prompt: '描述普通人的居住、饮食、教育、工作、家庭、娱乐及人生路径；写实际生活，不重复文化价值观或开场事件。',
  },
  {
    id: 'history.past',
    layer: 'history',
    section: '历史与现状',
    field: '关键历史',
    title: '关键历史与沉淀事件',
    hint: '奠定当下社会格局的重大历史转折、历史创伤或未解之谜。',
    placeholder: '例如：十年前海啸冲垮了旧港区，灾变遗址至今仍被列为隔离禁区。',
    prompt: '选择形成当下格局的少数关键事件，说明先后与遗留影响；不必从创世起写，不预定未来主线。',
  },
  {
    id: 'history.present',
    layer: 'history',
    section: '历史与现状',
    field: '当下局势',
    title: '当前局势与暗潮',
    hint: '当下所处的发展阶段、表面和平状态以及暗中滋生的矛盾变数。',
    placeholder: '例如：表面维持着停火协议，但随着新资源矿脉发现，暗中摩擦加剧。',
    prompt: '描述现在的发展阶段、稳定状态或正在发生的变化；不重复历史，不强加危机、主角使命或开场事件。',
  },
  {
    id: 'history.factions',
    layer: 'history',
    section: '历史与现状',
    field: '主要势力与关系',
    title: '主要阵营与势力博弈',
    hint: '关键国家、组织或群体的核心立场、资源优势与竞合对抗关系。',
    placeholder: '例如：港口行会与巡逻宪兵队面和心不和，地下走私网络渗透极深。',
    prompt: '描述重要国家、组织或群体的目标、资源、立场及合作竞争；与已有制度一致但不重写制度，不限于第一幕参与者。',
  },
] as const;
export function emptyWorldSections(): Pick<OpeningFormSnapshot, WorldSection> {
  return {
    世界基础: { 世界概况: '', 底层规律: '', 地理生态与资源: '', 居民与族群: '', 技术与特殊力量: '' },
    社会生活: { 权力与制度: '', 经济与基础设施: '', 文化信仰与价值观: '', 日常生活: '' },
    历史与现状: { 关键历史: '', 当下局势: '', 主要势力与关系: '' },
  };
}
