import type { OpeningFormSnapshot } from './opening';
export type WorldSection = '世界基础' | '社会生活' | '历史与现状';
export const worldFields = [
  {
    id: 'foundation.overview',
    layer: 'foundation',
    section: '世界基础',
    field: '世界概况',
    title: '你想走进怎样的世界？',
    hint: '现实都市、远未来，还是另一个完全不同的世界？',
    placeholder: '例如：一座人与妖怪共同生活的现代海滨城市。',
    prompt: '说明现实或架空、时代定位，以及世界的一句话特征。只写总览，不展开地理、制度和剧情。',
  },
  {
    id: 'foundation.laws',
    layer: 'foundation',
    section: '世界基础',
    field: '底层规律',
    title: '这里有什么特别的规律？',
    hint: '在这里，哪些现实中不可能的事会发生？',
    placeholder: '例如：梦里的伤口会留到醒来，但只有做梦的人看得见。',
    prompt: '描述自然、生命、时空等底层规律及边界；不写国家法律、科技清单或编辑器机制。普通现实规律无需逐条复述。',
  },
  {
    id: 'foundation.geography',
    layer: 'foundation',
    section: '世界基础',
    field: '地理生态与资源',
    title: '这片世界是什么样的？',
    hint: '山川、气候、动植物，或是人们争相寻找的资源。',
    placeholder: '例如：城市沿海而建，内陆常年被大雾笼罩。',
    prompt: '描述主要地域、气候、生态、关键资源与分布，以及环境的实际限制；不指定开场落脚点，不展开经济制度。',
  },
  {
    id: 'foundation.inhabitants',
    layer: 'foundation',
    section: '世界基础',
    field: '居民与族群',
    title: '这里生活着哪些人？',
    hint: '只有人类，还是也有其他族群？他们有什么不同？',
    placeholder: '例如：人类与长寿的海民杂居，海民每月都要回海里休养。',
    prompt: '描述居民、族群的生理或寿命差异、分布与生存需求；不创造具体 NPC 档案，不把同一族群写成同一种性格。',
  },
  {
    id: 'foundation.technology',
    layer: 'foundation',
    section: '世界基础',
    field: '技术与特殊力量',
    title: '这里有怎样的科技或特殊能力？',
    hint: '人们能用它们做什么？是人人都会，还是少数人的本事？',
    placeholder: '例如：大多数人用普通家电，少数工匠能把记忆封进物件。',
    prompt: '描述原有技术或力量能做什么、谁可获得、普及程度与代价；不写现实编辑器，不重复自然公理或制度全文。',
  },
  {
    id: 'society.institutions',
    layer: 'society',
    section: '社会生活',
    field: '权力与制度',
    title: '这里由谁说了算？',
    hint: '谁掌权，有哪些规矩？不同身份的人过得一样吗？',
    placeholder: '例如：各城区自治，外来者需要本地居民担保才能定居。',
    prompt: '描述治理、法律、身份、阶层、权利和义务；不列具体势力的目标和联盟，不以主角遭遇代替制度。',
  },
  {
    id: 'society.economy',
    layer: 'society',
    section: '社会生活',
    field: '经济与基础设施',
    title: '大家靠什么生活？',
    hint: '怎样赚钱、买东西、出远门，或与远方的人联系？',
    placeholder: '例如：港口贸易养活了多数居民，城区之间有通宵渡轮。',
    prompt: '描述生产、生计、交易、分配、交通、通信与公共服务；可以推导技术的生产影响，但不重复技术原理或文化信条。',
  },
  {
    id: 'society.culture',
    layer: 'society',
    section: '社会生活',
    field: '文化信仰与价值观',
    title: '人们相信什么、在意什么？',
    hint: '这里的人敬重什么，又有什么忌讳？',
    placeholder: '例如：人们相信海会记住承诺，因此从不在岸边轻易起誓。',
    prompt: '描述居民相信、重视与忌讳什么，以及群体间的观念差异；不重复作息生活清单，不把信仰自动写成客观真相。',
  },
  {
    id: 'society.daily',
    layer: 'society',
    section: '社会生活',
    field: '日常生活',
    title: '普通人的一天怎么过？',
    hint: '住在哪里、吃什么，忙完一天后又会去哪里？',
    placeholder: '例如：傍晚收工后，人们喜欢在码头的小摊吃饭聊天。',
    prompt: '描述普通人的居住、饮食、教育、工作、家庭、娱乐及人生路径；写实际生活，不重复文化价值观或开场事件。',
  },
  {
    id: 'history.past',
    layer: 'history',
    section: '历史与现状',
    field: '关键历史',
    title: '过去发生过哪些大事？',
    hint: '挑几件到今天仍有人记得、仍有影响的事就好。',
    placeholder: '例如：十年前的大潮淹没了旧港，许多人至今没有搬回去。',
    prompt: '选择形成当下格局的少数关键事件，说明先后与遗留影响；不必从创世起写，不预定未来主线。',
  },
  {
    id: 'history.present',
    layer: 'history',
    section: '历史与现状',
    field: '当下局势',
    title: '如今的日子怎么样？',
    hint: '眼下是安稳太平，还是有些事情正在悄悄改变？',
    placeholder: '例如：新航线开通后，陌生面孔越来越多，城里热闹起来。',
    prompt: '描述现在的发展阶段、稳定状态或正在发生的变化；不重复历史，不强加危机、主角使命或开场事件。',
  },
  {
    id: 'history.factions',
    layer: 'history',
    section: '历史与现状',
    field: '主要势力与关系',
    title: '有哪些重要的势力？',
    hint: '哪些组织值得一提？它们想要什么，彼此关系如何？',
    placeholder: '例如：船工行会与港口商会长期合作，却对新码头的归属各有打算。',
    prompt: '描述重要国家、组织或群体的目标、资源、立场及合作竞争；与已有制度一致但不重写制度，不限于第一幕参与者。',
  },
] as const;
export function emptyWorldSections(): Pick<OpeningFormSnapshot, WorldSection> {
  return {
    世界基础: { 世界概况: '', 底层规律: '', 地理生态与资源: '', 居民与族群: '', 技术与特殊力量: '' },
    社会生活: { 权力与制度: '', 经济与基础设施: '', 文化信仰与价值观: '', 日常生活: '' },
    历史与现状: { 关键历史: '', 当下局势: '', 主要势力与关系: '' },
  };
}
